### ISSUE TITLE
Local environment

### ISSUE THREAD

**Issue by zrajic** [jkrajinovic/dms#13]
What setup will be used for project?

**Comment by jkrajinovic** [comment]
As discussed docker with introduction would be great.

**Comment by zrajic** [comment]
@jkrajinovic can you pull `docker-setup` branch and start docker. application is running normally and there is no error but when i try to go to localhost:5000 there is connection refused error.

**Comment by jkrajinovic** [comment]
Sure as soon as I manage I'll try and get back. Thanks.

**Comment by zrajic** [comment]
@jkrajinovic great in the meantime i'll try to figure it out and get it to display right stuff

**Comment by jkrajinovic** [comment]
Closed with #16
